version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount the project directory
      - .:/app
      # But don't mount over the installed node_modules
      - /app/node_modules
    # Keep the container running in detached mode
    stdin_open: true
    tty: true